// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd7df68kuoq5CmcAPZBn_lW5VH8CgHqlM',
    appId: '1:125944911125:web:2dd5f209a40bfda008851c',
    messagingSenderId: '125944911125',
    projectId: 'green-minds-f15f5',
    authDomain: 'green-minds-f15f5.firebaseapp.com',
    databaseURL: 'https://green-minds-f15f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-minds-f15f5.firebasestorage.app',
    measurementId: 'G-VLBGBG1C1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rjGglgmOm4rjgEnAWOVXyUgcA2yM2XQ',
    appId: '1:125944911125:android:7376102a9000c68308851c',
    messagingSenderId: '125944911125',
    projectId: 'green-minds-f15f5',
    databaseURL: 'https://green-minds-f15f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-minds-f15f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQXWc0vsK3aQNn02T9pGii34Pt2ESsuU',
    appId: '1:125944911125:ios:f1db3951fae34c0808851c',
    messagingSenderId: '125944911125',
    projectId: 'green-minds-f15f5',
    databaseURL: 'https://green-minds-f15f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-minds-f15f5.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQXWc0vsK3aQNn02T9pGii34Pt2ESsuU',
    appId: '1:125944911125:ios:f1db3951fae34c0808851c',
    messagingSenderId: '125944911125',
    projectId: 'green-minds-f15f5',
    databaseURL: 'https://green-minds-f15f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-minds-f15f5.firebasestorage.app',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd7df68kuoq5CmcAPZBn_lW5VH8CgHqlM',
    appId: '1:125944911125:web:be7a0f85340bdee308851c',
    messagingSenderId: '125944911125',
    projectId: 'green-minds-f15f5',
    authDomain: 'green-minds-f15f5.firebaseapp.com',
    databaseURL: 'https://green-minds-f15f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-minds-f15f5.firebasestorage.app',
    measurementId: 'G-FPVGTM0HXF',
  );
}
